import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col  justify-evenly items-center">
          <div
            className={
              "flex flex-col align-middle items-center justify-between gap-5 px-12 py-9"
            }
          >
            {children}
          </div>
          <p className="text-slate-400 text-sm">
            © 2045 All Rights Reserved By Ilman Teguh Prasetya
          </p>
        </div>
      </body>
    </html>
  );
}
